apiVersion: v1
kind: Service
metadata:
  name: redis-secondary
  labels:
    app: redis-secondary
spec:
  ports:
  - port: 6379
    name: redis-secondary
  selector:
    app: redis-secondary
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-secondary
spec:
  serviceName: redis-secondary
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-secondary
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-secondary
        image: anubhavmishra/redis:3.2
        imagePullPolicy: Always
        env:
        - name: REPLICA
          value: "true"
        - name: REDIS_PASSWORD
          value: ""
        ports:
        - containerPort: 6379
          name: redis-secondary
        volumeMounts:
        - name: redis-secondary-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-secondary-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
